server:
  port: 9528
spring:
  application:
    name: MICROSERVICE-ZUUL-GATEWAY
zuul:
  routes:
    myUser.serviceId: xianggou-plat #这是调用满足条件的服务名，注意要小写
    myUser.path: /user/** #这是所有路径前的通配
  ignored-services: "*" #用*来通配符，忽略从9528端口通过服务名来调用
  prefix: "/services" #这是所有路径的前缀